import { Experience } from "@types";

export const experiences: Experience[] = [
  {
    title: "Senior Front-end Developer",
    companyShort: "FirstDecision",
    company: "First Decision",
    dateStart: "12.2023",
    dateEnd: "Present",
    description: [
      "- Actively engaged in the development and supervision of multiple projects, orchestrating the integration of innovative front-end solutions utilizing React.js, **Next.js 14**, **MUI**, **TypeScript**. The primary focus remains on optimizing user experience and enhancing the efficiency of web development processes.",
      "- Collaborating seamlessly with cross-functional teams, adeptly utilizing Git for precise version control and ensuring a smooth orchestration of project activities.",
      "- Taking charge of the oversight concerning the maintenance and deployment facets of **GitLab** projects through the proficient application of **Rancher** and **SonarQube**. Concurrently, offering valuable support and strategic guidance on the organization and utilization of projects within GitLab.Actively engaged in the development and supervision of multiple projects, orchestrating the integration of innovative front-end solutions. The primary focus remains on optimizing user experience and enhancing the efficiency of web development processes. Collaborating seamlessly with cross-functional teams, adeptly utilizing Git for precise version control and ensuring a smooth orchestration of project activities. Taking charge of the oversight concerning the maintenance and deployment facets of GitLab projects through the proficient application of Rancher and SonarQube. Concurrently, offering valuable support and strategic guidance on the organization and utilization of projects within GitLab.",
    ],
  },
  {
    title: "Senior Front-end Developer",

    companyShort: "TTY",
    company: "TTY2000",
    dateStart: "04.2023",
    dateEnd: "12.2023",
    description: [
      "- Actively developing and integrating innovative front-end solutions using **React**, **Next 13**, **MUI**, **TypeScript**, and **Tailwind CSS**, optimizing user experience and streamlining web development processes.",
      "- Revitalizing front-end interfaces of legacy systems by **incorporating modern technologies** and **refactoring HTML and CSS code in PHP projects**, adhering to Clean Code principles for ease of maintenance.",
      "- Employing **Docker** and **Nest.js** for effective project management and streamlined deployment.",
      "- Cooperating with **cross-functional teams**, leveraging Git for efficient version control and seamless project coordination.",
      "- Overseeing maintenance of **Azure DevOps** projects, offering support and guidance on project organization and utilization within the tool.",
    ],
  },
  {
    title: "Front-end Developer & UX Consultant",
    companyShort: "TTY",
    company: "TTY2000",
    dateStart: "09.2022",
    dateEnd: "04.2023",
    description: [
      "- Developed and implemented robust front-end solutions using **React**, **Next 13**, **MUI 5**, **TypeScript**, and **Tailwind CSS**, ensuring optimal user experience and seamless web development.",
      "- Worked on two fronts: one with **Next 13** and **MUI 5**, and another with **C#** using **Blazor**, **SASS**, and **MudBlazor** development.",
      "- Updated front-end interfaces of legacy systems using new technologies and refactored HTML and CSS code in PHP projects following the principles of Clean Code to facilitate maintenance.",
      "- Utilized **Docker** and **Nest** for efficient project management and deployment.",
      "- Leveraged advanced **UX Design** techniques to create visually appealing and user-friendly interfaces.",
      "- Collaborated with cross-functional teams, utilizing **Git** for efficient version control and seamless project coordination.",
    ],
  },
  {
    title: "Front-end Developer",
    companyShort: "AGU",
    company: "Advocacia-Geral da União",
    dateStart: "01.2022",
    dateEnd: "09.2022",
    description: [
      "- Developed **responsive and accessible** front-end solutions for internal **legacy** systems dating back from the 2000s, using **HTML**, **JavaScript**, **TypeScript**, and **Tailwind CSS**, enhancing user experience and ensuring seamless web development.",
      "- Utilized CSS frameworks like **Bootstrap**, **Tailwind CSS**, and **Bulma**, as well as Vanilla CSS 3.0, to create visually appealing and functional interfaces.",
      "- Employed **JavaScript frameworks** like **React**, **Vue**, and **Angular** for efficient front-end development.",
      "- Collaborated with the design team to implement **UX concepts** and visual designs, employing **Blazor** and **SASS** for efficient development.",
      "- Utilized **Git** for version control and project collaboration, working closely with cross-functional teams to ensure timely delivery and high-quality results.",
    ],
    linkTo: "/advocacia-geral-da-uniao",
  },
  {
    title: "Senior UI/UX Designer",
    companyShort: "AGU",
    company: "Advocacia-Geral da União",
    dateStart: "09.2018",
    dateEnd: "01.2022",
    description: [
      "- Conceptualized and designed visually appealing **web interfaces**, focusing on **user experience** and ensuring consistency across digital platforms.",
      "- Analyzed functional and non-functional requirements documentation, managed **SCRUM teams**, and improved the experience and UI of in-house governmental software.",
      "- Performed front-end modifications in service management system software and created an internal events management mobile app for the courses and events ministered by the 'School of Advocacia-Geral da União' using the **Microsoft PowerApps** platform, serving more than 1,000 users.",
      "- Utilized **Adobe Creative Suite**, **Figma**, and **Microsoft PowerApps** for design and prototyping, creating innovative and engaging content.",
      "- Collaborated with developers to implement designs, ensuring seamless integration with front-end development technologies.",
      "- Contributed to the creation of logos, branding materials, and web content, utilizing **Adobe InDesign** and other design tools to deliver high-quality visual assets.",
    ],
    linkTo: "/advocacia-geral-da-uniao",
  },
  {
    title: "UI/UX Designer",
    companyShort: "BBTS",
    company: "Banco do Brasil Tecnologia & Serviços",
    dateStart: "04.2015",
    dateEnd: "09.2018",
    description: [
      "- Designed and developed **user interfaces** for various digital platforms, focusing on **user experience** and visual appeal.",
      "- Crafted **wireframes**, **mockups**, and **high-fidelity prototypes** using Axure RP to validate documentation and improve user experience and design through extensive testing with clients.",
      "- Collaborated in in-house projects, designing financial management software for companies (bank clients), **front-end development/maintenance**, and designing/prototyping functionalities and visual identity for the mobile app 'Banco do Brasil,' one of the most used apps in Brazil with 50+ million downloads, 4 million reviews, and a 4.5 rating on Google Play.",
      "- Utilized **Axure RP**, **Figma**, **Adobe Creative Suite**, and other design tools to create high-fidelity prototypes and design concepts.",
      "- Collaborated with **cross-functional teams** to implement designs, ensuring seamless integration with **front-end development technologies**.",
      "- Contributed to digital photography and content creation initiatives, enhancing the visual appeal and effectiveness of web platforms and marketing materials.",
    ],

    linkTo: "/banco-do-brasil",
  },
  {
    title: "Administrative Assistant",
    companyShort: "CAER",
    company: "Companhia de Águas e Esgotos de Roraima",
    dateStart: "12.2012",
    dateEnd: "06.2011",
    description: [
      "- Assisted in the preparation and analysis of **financial documents**, including trial balances, ledgers, statements of movement by accounts, and balance sheets, contributing to the overall financial management of the organization.",
      "- Managed data entries using **TOTVS systems** manually or employing **MySQL** language when necessary, maintaining accurate financial records.",
    ],
  },
];
