import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CssBaseline, ThemeProvider, createTheme, Box } from "@mui/material";
import { Header, Providers } from "@components";
import {} from "@mui/system";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guilherme Bermêo - Senior Front-end Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Providers>
        <CssBaseline />
        <html lang="en">
          <Header />
          <Box className={inter.className} sx={{ p: 4, mt: 8 }}>
            {children}
          </Box>
        </html>
      </Providers>
    </>
  );
}
