import type { NextPage } from "next";
import Head from "next/head";
import { About } from "../components/sections/About";
import { Hero } from "../components/sections/Hero";
import { NavBar } from "../components/NavBar/NavBar";
import { Experience } from "../components/sections/Experience";

const Home: NextPage = () => {
  return (
    <>
      <NavBar />
      <Head>
        <title>Guilherme Bermêo - Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-8">
        <Hero />
        <About />
        <Experience />
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
