import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Hero } from "../components/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Guilherme Bermêo - Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className="container mx-auto">
        <h1 className="testeGlobal m-8 text-center text-3xl font-bold underline">
          Hello world!
        </h1>
        I am an experienced Front-end Designer with several years of experience
        working with governmental clients. Focused to create and enhance the
        aesthetics and experience of digital products. Adept in designing,
        managing, and planning the production of projects, ranging from small to
        very large-scale. An easy learner with a natural ability to collaborate
        and lead as a dynamic and dedicated professional. When I am not working,
        I study audio design, play board games, and watch tv shows.
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
