import type { Metadata } from "next";
import { CssBaseline, Box } from "@mui/material";
import { Header, Providers } from "@/components";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Guilherme Bermêo - Senior Front-end Developer",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "br" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: "en" | "br" };
}) {
  let messages;
  try {
    messages = (await import(`../../../data/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <>
      <Providers>
        <CssBaseline />
        <html lang={locale}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            <Box sx={{ p: 4, mt: 8 }}>{children}</Box>
          </NextIntlClientProvider>
        </html>
      </Providers>
    </>
  );
}
